### ISSUE TITLE
Own data using .db file shows nothing

### ISSUE THREAD

**Issue by fburdet** [OpenBioLink/Explorer#15]
Hello,

I added a config as specified for my own .db file from safran.
I named the db file as instructed: {ID of dataset}_{ID of explanation}.db and put it in server/db.

I can see the dataset added on the :5000 page.
The blazegraph server works and it seems that the connection from LinkExplorer is successful (at least no error message. No message at all actually)

But after clicking Next and Done, no entities are displayed. Just an empty browsing page with "1" and arrows, but nothing more, and nothing in the Quicksearch.

Any way to debug  that and understand what could be the issue?

Thanks in advance!

**Comment by nomisto** [comment]
Hello, 
That is strange, you created the db file yourself right?
I've now hosted the db files we generated [here](https://zenodo.org/record/6669241). If you generated it yourself, maybe this is an issue with SAFRAN. Could you make sure that your db-File contains edges? Either by comparing file sizes or with an sqlite explorer like https://sqlitebrowser.org/ ?

**Comment by fburdet** [comment]
Hello,

Thanks for checking!

Yes, I did create the .db myself using the safran version with explanation.

Thanks for putting the db files online. I downloaded wn18rr_nrno.db, renamed it to adsicore_max.db (in index.json, dataset "ID" is "adsicore" and Explanation "ID" is "max".
I relaunched the docker.
I still get a void web page :(
Should it have worked like this? I didn't change the RDF enpoint, should it match exactly what is in the explanation db? Should the method be correct in the metadata?

I opened my .db in an sqlite explorer. In which table should I look for edges?
I do see data in all 6 tables at least.

**Comment by nomisto** [comment]
The endpoint "http://explore.ai-strategies.org:9999/blazegraph/namespace/wn18rr/sparql" does not exist on your machine right? So this is why you get a void web page.

So you have to either:
1) set `"Endpoint": ""` to an empty string: Here entities and rels appear as they appear in the KG (I fixed a small bug, so please pull for that :))
or
2) set `Endpoint` to an endpoint that exists and gives valid labels for your entities

**Comment by nomisto** [comment]
So this is more work than expected, unfortunately I did not test the "No rdf graph" too extensively. A qick workaround would be if you don't want to use the RDF graph (which provides edges, labels, descriptions, ...) is to set `"Endpoint": "http://{yourhost}:9999/blazegraph/namespace/kb/sparql"`, which points by default to an empty RDF graph. ({replace "yourhost" with "blazegraph" if you are using docker)

**Comment by fburdet** [comment]
Thanks for checking!

I pulled and tried 
- the empty string in index.json
- the empty kb also in index.json as http://blazegraph:9999/blazegraph/namespace/kb/sparql
- and then upload part of the triplets in kb from the blazegraph web interface
 
Nothing happens. I still see 0 entities.

I am wondering if the system sees my .db at all. Remember it also didn't work with the .db that you produced yourself, and an empty (but running) blazegraph. All in Docker.

**Comment by fburdet** [comment]
By the way, I wanted to check back how your online version behaves, but the links seem broken, eg
http://explore.ai-strategies.org/hetio/nrno/entity?term=Compound::DB01403

**Comment by nomisto** [comment]
Oh thanks, should work again!

**Comment by nomisto** [comment]
Could you please try again (repull) and before that delete the IndexedDb of LinkExplorer in your browser:

Chrome: F12 -> Application -> IndexedDB -> Linkexplorer - http://localhost:5000 -> Delete database
Firefox: F12 -> Web Storage -> Indexed DB -> http://http://localhost:5000 -> Right click on Linkexplorer (default) -> Delete Linkexplorer (default)

**Comment by nomisto** [comment]
Great, sorry for the hassle! 
Yes please, could you also provide the config that you used?

**Comment by fburdet** [comment]
Done for SAFRAN!

But the link 
http://explore.ai-strategies.org/
is still broken at least in my browser

**Comment by nomisto** [comment]
Could you try a different browser/device? I tried it from three different browsers/devices and everyone worked.

**Comment by fburdet** [comment]
Ah it's working again, good!

**Comment by fburdet** [comment]
This issue can be closed, thanks!
